Database initialization support
exilespirit/spring_task_manager pull request #2
Opened 2018-07-05 08:44 UTC by exilespirit

Adding database initialization support.
Configuring properties to create new database and populate it with mock data from SQL script files

2018-07-05 17:38 UTC, dmol5E requested changes
Необходимо убрать лишний код

2018-07-05 17:38 UTC, REmindER36 commented on src/main/resources/application.properties
> +spring.datasource.initialize=true
Зачем это свойство? На сколько мне известно в твоей версии spring-boot этой проперти нету.

2018-07-05 17:38 UTC, REmindER36 commented on src/main/java/task_manager/Application.java
> +
Без этого кода вообще инициализация не проходит? Зачем тогда остался DROP DATABASE в скрипте?

2018-07-05 18:52 UTC, exilespirit commented on src/main/java/task_manager/Application.java
> +
Если база создана и в базе уже есть таблицы, то без DROP будет выдавать ошибку.
Можно сделать IF NOT EXISTS при создании каждой таблицы вместо этой строки, если так будет удобнее

2018-07-06 04:54 UTC, REmindER36 commented on src/main/java/task_manager/Application.java
> +
У тебя в двух местах CREATE DATABASE. Нельзя это делать один раз в скрипте?

2018-07-06 06:05 UTC, exilespirit commented on src/main/java/task_manager/Application.java
> +
Spring пытается подключиться к DataSource до того, как запускает скрипт. Из-за этого, если в MySql нет базы TaskManager, он выдает Exception и дальше не работает. Поэтому я добавил код при запуске приложения в класс Application (писал, что решение некрасивое, но работает). 
Код в скрипте нужен в случае, если в базе данных уже есть TaskManager с таблицами и данными в них. Он все очищает и создает заново базу и затем наполняет ее  из data.sql

2018-07-06 06:07 UTC, dmol5E approved these changes

2018-07-06 06:07 UTC, merged